### ISSUE TITLE
Fails when unpacking rocket league UPK's

### ISSUE THREAD

**Issue by JABirchall** [EliotVU/Unreal-Library#26]
When attempting to decompile rocketleague UPK's the application crashes with multiple error messages.

When unpacking TAGame.upk
```
Thrown by:LoadPackage
   at UEExplorer.UI.Tabs.UC_PackageExplorer.LoadPackage()
   at UEExplorer.UI.ProgramForm.LoadFile(String fileName)System.OverflowException: Array dimensions exceeded supported range.
   at UELib.UnrealReader.ReadText()
   at UELib.UNameTableItem.Deserialize(IUnrealStream stream)
   at UELib.UnrealPackage.Deserialize(UPackageStream stream)
   at UELib.UnrealLoader.LoadPackage(String packagePath, FileAccess fileAccess)
   at UEExplorer.UI.Tabs.UC_PackageExplorer.LoadPackage()
```

When unpacking TAGame_LOC_INT.upk
```
Thrown by:LoadPackage
   at UEExplorer.UI.Tabs.UC_PackageExplorer.LoadPackage()
   at UEExplorer.UI.ProgramForm.LoadFile(String fileName)System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt64()
   at UELib.UNameTableItem.Deserialize(IUnrealStream stream)
   at UELib.UnrealPackage.Deserialize(UPackageStream stream)
   at UELib.UnrealLoader.LoadPackage(String packagePath, FileAccess fileAccess)
   at UEExplorer.UI.Tabs.UC_PackageExplorer.LoadPackage()
```

**Comment by RenegadeWraith** [comment]
Doesn't Rocket League have encryption? I don't see how you're decrypting it in the commit.

**Comment by EliotVU** [comment]
> Doesn't Rocket League have encryption? I don't see how you're decrypting it in the commit.

Yeah, UELib assumes that you decrypt the package before hand, using a third party tool.
