### ISSUE TITLE
Support for Asura's Wrath (PS3/360)

### ISSUE THREAD

**Issue by CoolnezX** [EliotVU/Unreal-Library#55]
Hey, I've been meaning to look at how Asura's Wrath game logic works and what dependencies it has on Unreal Engine 3, but for some reason the Unreal Explorer/Unreal Library cannot decompile any of the classes in the games main .XXX file. I stepped through the function that handles the decompilation with DnSpy midway through the decompilation and saw some errors. I decided to jot them down to see if these could be of any help getting support for it. 

(This is my first time writing an issue on this site, so sorry if there any mistakes that are common in this!)

```
BCAI_EnemyBossCbt06

Unable to cast object of type 'UELib.Core.UNameProperty' to type 'UELib.Core.UTextBuffer'
StackTrace	" at UELib.UnrealStreamImplementations.ReadObject[T](IUnrealStream stream)\r\n   
                          at UELib.Core.UStruct.Deserialize()\r\n   
			  at UELib.Core.UFunction.Deserialize()\r\n   
			  at UELib.Core.UObject.BeginDeserializing()" string

Unable to cast object of type 'UELib.Core.UFunction' to type 'UELib.Core.UTextBuffer'
StackTrace	"   at UELib.UnrealStreamImplementations.ReadObject[T](IUnrealStream stream)\r\n   
                            at UELib.Core.UStruct.Deserialize()\r\n
			    at UELib.Core.UFunction.Deserialize()\r\n
			    at UELib.Core.UObject.BeginDeserializing()"	string

				
AnimNameEd(4042) 
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
StackTrace "   at System.IO.__Error.EndOfFile()\r\n   
               at System.IO.BinaryReader.FillBuffer(Int32 numBytes)\r\n   
               at System.IO.BinaryReader.ReadInt32()\r\n   
               at UELib.UnrealReader.ReadIndex()\r\n   
               at UELib.UnrealReader.ReadNameIndex(Int32& num)\r\n   
			   at UELib.UObjectStream.ReadNameIndex(Int32& num)\r\n   
			   at UELib.UnrealStreamImplementations.ReadNameReference(IUnrealStream stream)\r\n   
			   at UELib.Core.UProperty.Deserialize()\r\n   
			   at UELib.Core.UObject.BeginDeserializing()"

			   
AnimNameSt(4043) 
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
StackTrace "   at System.IO.__Error.EndOfFile()\r\n   
               at System.IO.BinaryReader.FillBuffer(Int32 numBytes)\r\n   
               at System.IO.BinaryReader.ReadInt32()\r\n   
               at UELib.UnrealReader.ReadIndex()\r\n   
               at UELib.UnrealReader.ReadNameIndex(Int32& num)\r\n   
			   at UELib.UObjectStream.ReadNameIndex(Int32& num)\r\n   
			   at UELib.UnrealStreamImplementations.ReadNameReference(IUnrealStream stream)\r\n   
			   at UELib.Core.UProperty.Deserialize()\r\n   
			   at UELib.Core.UObject.BeginDeserializing()"
	
HomingRate(4045)	
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
			   at System.IO.__Error.EndOfFile()
			   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
			   at System.IO.BinaryReader.ReadInt32()
			   at UELib.UnrealReader.ReadIndex()
			   at UELib.UnrealReader.ReadNameIndex(Int32& num)
			   at UELib.UObjectStream.ReadNameIndex(Int32& num)
			   at UELib.UnrealStreamImplementations.ReadNameReference(IUnrealStream stream)
			   at UELib.Core.UProperty.Deserialize()
			   at UELib.Core.UObject.BeginDeserializing()}	System.IO.EndOfStreamException

ExecBehaviorShockWave(4049)
System.InvalidCastException: Unable to cast object of type 'UELib.Core.UIntProperty' to type 'UELib.Core.UTextBuffer'.
			   at UELib.UnrealStreamImplementations.ReadObject[T](IUnrealStream stream)
			   at UELib.Core.UStruct.Deserialize()
			   at UELib.Core.UFunction.Deserialize()
			   at UELib.Core.UObject.BeginDeserializing()}	System.InvalidCastException

EndVajraMode(4063)
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
			   at System.IO.__Error.EndOfFile()
			   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
			   at System.IO.BinaryReader.ReadInt32()
			   at UELib.UnrealReader.ReadIndex()
			   at UELib.UnrealReader.ReadNameIndex(Int32& num)
			   at UELib.UObjectStream.ReadNameIndex(Int32& num)
			   at UELib.UnrealStreamImplementations.ReadNameReference(IUnrealStream stream)
			   at UELib.Core.UProperty.Deserialize()
			   at UELib.Core.UObject.BeginDeserializing()}	System.IO.EndOfStreamException

BCAI_EnemyBossCbt06(4083)
System.InvalidCastException: Unable to cast object of type 'UELib.Core.UFunction' to type 'UELib.Core.UTextBuffer'.
			   at UELib.UnrealStreamImplementations.ReadObject[T](IUnrealStream stream)
			   at UELib.Core.UStruct.Deserialize()
			   at UELib.Core.UState.Deserialize()
			   at UELib.Core.UClass.Deserialize()
			   at UELib.Core.UObject.BeginDeserializing()}	System.InvalidCastException
```

**Comment by EliotVU** [comment]
You need to configure UE Explorer to load the package as a console-cooked package.

**Comment by CoolnezX** [comment]
Ah! So that was the problem... 
Thank you for your support! This tool is pretty awesome!

**Comment by EliotVU** [comment]
Great!
