### ISSUE TITLE
Some L2 Decompilation issues

### ISSUE THREAD

**Issue by devmagik** [EliotVU/Unreal-Library#94]
Tried decompiling .u file and received few issues, i'm trying to jingle my head around though - no luck :(

```
function setShowStep(int stepNum)
{
    local int i;

    currentFormStepNum = stepNum;
    // End:0x1BB
    if(stepNum == 1)
    {
        GetMeButton("Storage_btn").EnableWindow();
        GetMeButton("History_btn").EnableWindow();
        GetMeWindow("GachaReward_wnd").ShowWindow();
        GetMeWindow("GachaBtn_wnd").ShowWindow();
        GetMeButton("GachaBtn_wnd.GachaExit_Btn").HideWindow();
        GetMeWindow("Result_wnd").HideWindow();
        GetMeWindow("GachaCost_wnd").ShowWindow();
        GetMeButton("Close_Btn").ShowWindow();
        GetMeTexture("ResultBg_tex").HideWindow();
        GetMeWindow("LeftTime_wnd").ShowWindow();
        i = 0;
        J0x154:

        // End:0x1AC [Loop If]
        if(i < ShowItemInfo.Length)
        {
            setDefaultShowItemInfo(i + 1, ShowItemInfo[i].RankType, ShowItemInfo[i].ItemType, ShowItemInfo[i].Amount);
            i++;
            // [Loop Continue]
            goto J0x154;
        }
        updateGachaBtn_wnd();
        checkGameStartButtonState();        
    }
    else
    {
        // End:0x481
        if(stepNum == 2)
        {
            GetMeButton("Close_Btn").HideWindow();
            // End:0x33E
            if((nVideoRankType == 1) || nVideoRankType == 2)
            {
                // End:0x294
                if(getInstanceUIData().GetIsClassicServer())
                {
                    SceneClipView(GetScript("SceneClipView")).customPlayUsm(-4, -6, 898, 624, 1, 4, "unique_01b_classic.usm", SceneClipView(GetScript("SceneClipView")).100002, "UniqueGacha");                    
                }
                else
                {
                    SceneClipView(GetScript("SceneClipView")).customPlayUsm(-4, -6, 898, 624, 1, 4, "unique_01b.usm", SceneClipView(GetScript("SceneClipView")).100002, "UniqueGacha");
                }
                SetUniqueGachaVideo(true);
                showDisable(true);
                GetMeWindow("GachaBtn_wnd").HideWindow();                
            }
            else
            {
                // End:0x3D7
                if(getInstanceUIData().GetIsClassicServer())
                {
                    SceneClipView(GetScript("SceneClipView")).customPlayUsm(-4, -6, 898, 624, 1, 4, "unique_01a_classic.usm", SceneClipView(GetScript("SceneClipView")).100003, "UniqueGacha");                    
                }
                else
                {
                    SceneClipView(GetScript("SceneClipView")).customPlayUsm(-4, -6, 898, 624, 1, 4, "unique_01a.usm", SceneClipView(GetScript("SceneClipView")).100003, "UniqueGacha");
                }
                SetUniqueGachaVideo(true);
                showDisable(true);
                GetMeWindow("GachaBtn_wnd").HideWindow();
            }            
        }
        else
        {
            // End:0x890
            if(stepNum == 3)
            {
                showDisable(false);
                SetUniqueGachaVideo(false);
                GetMeButton("Storage_btn").DisableWindow();
                GetMeButton("History_btn").DisableWindow();
                GetMeWindow("GachaReward_wnd").HideWindow();
                GetMeWindow("GachaBtn_wnd").HideWindow();
                GetMeWindow("Result_wnd").ShowWindow();
                GetMeTextBox("Result_wnd.ResultConfirm_txt").ShowWindow();
                GetMeButton("Result_wnd.ResultConfirm_btn").ShowWindow();
                GetMeTexture("ResultBg_tex").ShowWindow();
                GetMeWindow("LeftTime_wnd").HideWindow();
                // End:0x63B
                if(bHasOnlyRHigherCard())
                {
                    GetMeButton("Result_wnd.ResultConfirm_btn").DisableWindow();
                    GetMeTextBox("Result_wnd.ResultConfirm_txt").SetText(GetSystemString(5235));                    
                }
                else
                {
                    GetMeButton("Result_wnd.ResultConfirm_btn").EnableWindow();
                    GetMeTextBox("Result_wnd.ResultConfirm_txt").SetText(GetSystemString(5234));
                }
                GetMeButton("Close_Btn").HideWindow();
                ShowAllMotionCards();
                // End:0x7B9
                if(gacha_game_packet.ResultItems.Length == 1)
                {
                    // End:0x75F
                    if((gacha_game_packet.ResultItems[0].cRankType == 2) || gacha_game_packet.ResultItems[0].cRankType == 1)
                    {
                        PlaySound("InterfaceSound.GachaJewel_DropB");
                        Debug("???? : InterfaceSound.GachaJewel_DropB");
                        goto J0x7B6;
                        PlaySound("InterfaceSound.GachaJewel_DropA");
                    }
                    Debug("???? : InterfaceSound.GachaJewel_DropA");
                    goto J0x88D;
                    // End:0x82A
                    if(highGradeCount > 0)
                    {
                    }
                    PlaySound("InterfaceSound.GachaJewel_DropB_small");
                    Debug("???? : InterfaceSound.GachaJewel_DropB_small");
                    goto J0x88D;
                    PlaySound("InterfaceSound.GachaJewel_DropA_small");
                }
                Debug("???? : InterfaceSound.GachaJewel_DropA_small");
                goto J0xC04;
                /* Statement decompilation error: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
                    
                */

                // End:0xC04
                /*@Error*/
            }
            showDisable(true);
            SetUniqueGachaVideo(false);
            GetMeWindow("Result_wnd").HideWindow();
            GetMeWindow("URReward_wnd").ShowWindow();
            GetMeWindow("URReward_wnd").SetFocus();
            GetMeEffectViewportWnd("URReward_wnd.UREffectViewport").SpawnEffect("LineageEffect.d_ar_attractcubic_ta");
            GetMeEffectViewportWnd("URReward_wnd.UREffectViewport02").SpawnEffect("LineageEffect2.ave_white_trans_deco");
            getInstanceL2Util().childWindowMoveToCenter(Me, GetMeWindow(m_Windowname $ ".URReward_wnd"));
            L2UITween(GetScript("l2UITween")).StartShake(m_Windowname $ ".URReward_wnd", 6, 1000, L2UITween(GetScript("l2UITween")).1, 0);
            // End:0xAC4
            if(IsAdenServer())
            {
                playNpcViewport(GetMeCharacterViewportWindow("URReward_wnd.Object01Viewport"), 9038, 170, 33000, 0, 0, 0.0000000, "", 1);
                playNpcViewport(GetMeCharacterViewportWindow("URReward_wnd.Object02Viewport"), 9039, 170, 33000, 0, 0, 0.0000000, "", 1);
                goto J0xBDE;
                // End:0xB5C
                if(getInstanceUIData().GetIsClassicServer())
                {
                }
                playNpcViewport(GetMeCharacterViewportWindow("URReward_wnd.Object01Viewport"), 9144, 170, 33000, 0, 0, 0.0000000, "", 1);
                playNpcViewport(GetMeCharacterViewportWindow("URReward_wnd.Object02Viewport"), 9145, 170, 33000, 0, 0, 0.0000000, "", 1);
                goto J0xBDE;
                playNpcViewport(GetMeCharacterViewportWindow("URReward_wnd.Object01Viewport"), 34788, 170, 33000, 0, 0, 0.0000000, "", 1);
            }
            playNpcViewport(GetMeCharacterViewportWindow("URReward_wnd.Object02Viewport"), 34789, 170, 33000, 0, 0, 0.0000000, "", 0);
            PlaySound("InterfaceSound.GachaJewel_Uniq");
            return;
            @NULL
            L2Util
        }
    }
}
```

In this function seems like block jump is not decompiled and @NULL added:
```
function setCardFront(int cardNum, optional bool noSound)
{
    local int Rank, ClassID;
    local INT64 Amount;
    local string bigString;

    Rank = gacha_game_packet.ResultItems[cardNum - 1].cRankType;
    ClassID = gacha_game_packet.ResultItems[cardNum - 1].nItemType;
    Amount = gacha_game_packet.ResultItems[cardNum - 1].nAmount;
    GetMeButton(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCard_btn").HideWindow();
    // End:0x2E5
    if(Rank == 1)
    {
        GetMeTextBox("URReward_wnd.URRewardName_txt").SetText(GetItemNameAllByClassID(ClassID));
        GetMeTextBox("URReward_wnd.URRewardNum_txt").SetText("x" $ (Amount));
        GetMeItemWindow("URReward_wnd.URRewardIcon_Itemwindow").Clear();
        GetMeItemWindow("URReward_wnd.URRewardIcon_Itemwindow").AddItem(GetItemInfoByClassID(ClassID));
        GetMeButton("Close_Btn").HideWindow();
        // End:0x25D
        if(getInstanceUIData().GetIsClassicServer())
        {
            SceneClipView(GetScript("SceneClipView")).customPlayUsm(-4, -6, 898, 624, 1, 4, "unique_02_classic.usm", SceneClipView(GetScript("SceneClipView")).100004, "UniqueGacha");            
        }
        else
        {
            SceneClipView(GetScript("SceneClipView")).customPlayUsm(-4, -6, 898, 624, 1, 4, "unique_02.usm", SceneClipView(GetScript("SceneClipView")).100004, "UniqueGacha");
        }
        SetUniqueGachaVideo(true);
        showDisable(true);
    }
    GetMeItemWindow(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardItem_itemwindow").ShowWindow();
    GetMeItemWindow(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardItem_itemwindow").Clear();
    GetMeItemWindow(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardItem_itemwindow").AddItem(GetItemInfoByClassID(ClassID));
    GetMeTextBox(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardItemNum_txt").ShowWindow();
    GetMeTextBox(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardItemNum_txt").SetText("x" $ (Amount));
    // End:0x67D
    if(Rank == 1)
    {
        GetMeEffectViewportWnd(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardOpenEffect02_tex").SpawnEffect("LineageEffect.d_ar_attractcubic_ta");
        GetMeAnimTexture(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardOpenEffect_tex").SetTexture("L2UI_NewTex.SideBar.SideBar_VP_Apply_Effect_00");
        AnimTexturePlay(GetMeAnimTexture(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardEffect02_tex"), true, 99999999);        
    }
    else
    {
        // End:0x80E
        if(Rank == 2)
        {
            GetMeEffectViewportWnd(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardOpenEffect02_tex").SpawnEffect("LineageEffect.d_ar_attractcubic_ta");
            GetMeAnimTexture(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardOpenEffect_tex").SetTexture("L2UI_NewTex.SideBar.SideBar_VP_Apply_Effect_00");
            AnimTexturePlay(GetMeAnimTexture(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardEffect02_tex"), true, 99999999);            
        }
        else
        {
            GetMeAnimTexture(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardOpenEffect_tex").SetTexture("L2UI_NewTex.SideBar.SideBar_VP_Apply_Effect_00");
            AnimTextureStop(GetMeAnimTexture(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardEffect02_tex"), true);
        }
    }
    nOpenURCardNum = cardNum;
    AnimTexturePlay(GetMeAnimTexture(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardOpenEffect_tex"), true, 1);
    // End:0x984
    if(currentGachaGameNum == 1)
    {
        bigString = "BIG";
    }
    GetMeTexture(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardBackBg_tex").SetTexture(((("L2UI_NewTex.UniqueGacha.UniqueGacha" $ (getCardType(cardNum))) $ bigString) $ "_") $ (getCardRankString(Rank)));
    GetMeTexture(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardBg_tex").ShowWindow();
    GetMeTexture(((("Result_wnd.ResultCard" $ (fillZeroString(2, string(cardNum)))) $ "_") $ bigCardPathAdd) $ "wnd.ResultCardBg02_tex").ShowWindow();
    // End:0xBBD
    if(noSound == false)
    {
        // End:0xB5A
        if(Rank == 3)
        {
            PlaySound("InterfaceSound.GachaJewel_Basic");
            Debug("????: InterfaceSound.GachaJewel_Basic");
            goto J0xBBD;
            // End:0xBBD
            if(Rank == 2)
            {
            }
            PlaySound("InterfaceSound.GachaJewel_Rare");
            Debug("????: InterfaceSound.GachaJewel_Rare");
            goto J0xBBD;
            // End:0xCB7
            if(bAllCardFront())
            {
            }
        }
        GetMeTextBox("Result_wnd.ResultConfirm_txt").HideWindow();
        GetMeButton("Result_wnd.ResultConfirm_btn").HideWindow();
        GetMeWindow("GachaBtn_wnd").ShowWindow();
        GetMeWindow("GachaBtn_wnd").SetFocus();
        updateGachaBtn_wnd();
        GetMeButton("GachaBtn_wnd.GachaExit_Btn").ShowWindow();
        // End:0xCB7
        if(GetUniqueGachaVideo() == false)
        {
            GetMeButton("Close_Btn").ShowWindow();
            // End:0xCF1
            if(bAllRCardFront())
            {
            }
        }
        GetMeButton("Result_wnd.ResultConfirm_btn").DisableWindow();
        goto J0xD1F;
        GetMeButton("Result_wnd.ResultConfirm_btn").EnableWindow();
    }
    return;
    @NULL
}
```

One more question would be handling INT64 (I would think that it's the case as initially where this exception was outputted the INT64 is placed)

```
            break;
        /* Statement decompilation error: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
            
        */

        // End:0x8D8
        /*@Error*/;
        // Failed to format nests!:System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at UELib.Core.UStruct.UByteCodeDecompiler.DecompileNests(Boolean outputAllRemainingNests)
   at UELib.Core.UStruct.UByteCodeDecompiler.Decompile()
        // 6 & Type:If Position:0x8D8
        // Failed to format remaining nests!:System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at UELib.Core.UStruct.UByteCodeDecompiler.DecompileNests(Boolean outputAllRemainingNests)
   at UELib.Core.UStruct.UByteCodeDecompiler.Decompile()
        // 6 & Type:If Position:0x8D8
 ```

**Comment by devmagik** [comment]
Anyways, I think it's because Lineage2 as a game is not supported for UE-Explorer
LicenseVersion 40. Version 133.
It goes down as Unkown BuildGame type, what I've seen it is missing 0x63 token, 0x5B and might miss others. I don't know if it fells under bug or  more likely unsupported type for this ticket. Still trying to understand UELib project to make changes accordingly

**Comment by EliotVU** [comment]
Yep, I think your best is to look at this particular commit https://github.com/EliotVU/Unreal-Library/commit/48b427f174f399222e2039cf43a368ed54fbf00a to understand how to implement support for custom property types.

**Comment by EliotVU** [comment]
Closing for the same reason as #108
